server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.38.55:32769/tensquare_qa?characterEncoding=UTF8
    username: ENC(aXAlpsgpE4eUTHJIbdl08g==)
    password: ENC(CLnWNP5OHbuSU83sBUtl3Q==)
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast
    ttl: 60000000000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
