server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.38.55:32769/tensquare_user?characterEncoding=UTF8
    username: ENC(aXAlpsgpE4eUTHJIbdl08g==)
    password: ENC(CLnWNP5OHbuSU83sBUtl3Q==)
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 47.107.38.55
  rabbitmq:
    host: 47.107.38.55
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
