server: 
  port: 9004
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.38.55:32769/tensquare_article?characterEncoding=UTF8
    username: ENC(aXAlpsgpE4eUTHJIbdl08g==)
    password: ENC(CLnWNP5OHbuSU83sBUtl3Q==)
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 47.107.38.55
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
